### ISSUE TITLE
Doing something wrong...

### ISSUE THREAD

**Issue by mischievous** [Magic-Unique/CommandLine#2]
This is my command:
test --scan /Volumes/Promise -NSDocumentRevisionsDebugMode YES

// calls to command line
CLCommand *cmd = [CLCommand mainCommand];

cmd.setQuery(@"scan").require();

[cmd handleProcess:^int (CLCommand *command, CLProcess *process)
{
    NSLog (@"%@", process.queries[@"scan"]);

    return EXIT_SUCCESS;
}];

//
CLCommandMain();

Output:
Error: illegal key `N`

**Comment by Magic-Unique** [comment]
When you typein an argument which has prefix `-`, it will be parsed as an abbr of a query or a flag.
So, -NSDocumentXXXX is meaning that -N -S -D -o -c -u -m -e -n -t ......

But -N is not a flag defined in `cmd`, so it throw an error.

**Comment by Magic-Unique** [comment]
You can also close the parsing rule:
```objc
cmd.allowInvalidKeys = YES; // force to parse unknow key
```

But the result (`progress` Instance)will not be expected.

**Comment by mischievous** [comment]
Ok.  Is there a way to pass tell your code to ignore the -NSDocumentRevisionsDebugMode and everything after it?

Thanks

**Comment by Magic-Unique** [comment]
All arg with `-` prefix will be parsed as one or more abbr.

There are some recommend definitions for it:

1. `$ test  --scan /Voluments/Promise --NSDocumentRevisionsDebugMode YES`

`NSDocumentRevisionsDebugMode` is a query with value `YES` 

2. `$ test --scan ... --key -NSDocumentRevisionsDebugMode --value YES`.
The `key` Is a query with value `-NSDocumentRevisionsDebugMode`.
The `value` is a query with value `YES`

**Comment by mischievous** [comment]
The problem is Apple in there infinite wisdom is adding the "-NSDocumentRevisionsDebugMode YES" for me.  Its not me, and its not in my test.  

Instead of you using '[NSProcessInfo.processInfo.arguments mutableCopy];' to get the arguments is there a function I can call to pass in the arguments myself?  or should I justcopy the CLProcess currentProcess method and and do what I need?  

I am try not to fork your code.

**Comment by Magic-Unique** [comment]
This problem is the parsing rule in CLProcess is not expected for you. I don’t know what do you want to do in the process handler block. The command is developed by yourself, so it’s arguments is defined by you, not Apple.

If you want to call Apple’s command line, you can append `-` manually in handler block.

I guess you want to make a command line and replace another that make by Apple? So you must simulate the same arguments?

**Comment by Magic-Unique** [comment]
I think it can resolve your problem.

First, set `allowInvalidKeys` to `YES`.

Second, read the arguments with `NSUserDefaults` or `NSProcess` instead of `CLProcess`

For default, arguments with `-` prefix will be set into `NSUserDefaults` automatically. It’s meaning that `[userDefaults boolForKey:@“NSDocumentRevisionsDebugMode”] == YES`.

Or you can also use `NSProcess.currentProcess.arguments` to get all plain arguments.

**Comment by mischievous** [comment]
I think we have a language problem... Now I am completely lost too.  

You are correct I define my own command line args, but because my program is an "App" and not a "Command Line" apple is adding the "-NSDocumentRevisionsDebugMode YES"  to the command line when calling the main function.  

I am not sure what I should do with NSUserDefaults? Use that in place of the Demo class in your examples?  

You think that is better than ...

NSMutableArray *arguments = NSProcessInfo.processInfo.arguments;
uint64_t idx;
idx = [arguments indexForObject:@"-NSDocumentRevisionsDebugMode]
while (idx < arguments.count)
    [arguments removeLastObject];
        CLCommand *command = [CLCommand commandWithArguments:arguments];
        _shared = [command processWithCommands:command.commandPatharguments:arguments];

**Comment by Magic-Unique** [comment]
I see....

`-NSDocumentRevisionsDebugMode` was passed by Finder. 

Copy an array and remove all invalid arguments before parsing is the best way.
